/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimpanPinjamRouteImport } from './routes/simpan-pinjam'
import { Route as ProdukDigitalRouteImport } from './routes/produk-digital'
import { Route as PosRouteImport } from './routes/pos'
import { Route as KeuanganRouteImport } from './routes/keuangan'
import { Route as InventoriRouteImport } from './routes/inventori'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EksporIndexRouteImport } from './routes/ekspor.index'
import { Route as AnggotaIndexRouteImport } from './routes/anggota.index'
import { Route as EksporPeluangRouteImport } from './routes/ekspor.peluang'
import { Route as EksporDokumenRouteImport } from './routes/ekspor.dokumen'
import { Route as AnggotaAnggotaIdRouteImport } from './routes/anggota.$anggotaId'

const SimpanPinjamRoute = SimpanPinjamRouteImport.update({
  id: '/simpan-pinjam',
  path: '/simpan-pinjam',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukDigitalRoute = ProdukDigitalRouteImport.update({
  id: '/produk-digital',
  path: '/produk-digital',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const KeuanganRoute = KeuanganRouteImport.update({
  id: '/keuangan',
  path: '/keuangan',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoriRoute = InventoriRouteImport.update({
  id: '/inventori',
  path: '/inventori',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EksporIndexRoute = EksporIndexRouteImport.update({
  id: '/ekspor/',
  path: '/ekspor/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnggotaIndexRoute = AnggotaIndexRouteImport.update({
  id: '/anggota/',
  path: '/anggota/',
  getParentRoute: () => rootRouteImport,
} as any)
const EksporPeluangRoute = EksporPeluangRouteImport.update({
  id: '/ekspor/peluang',
  path: '/ekspor/peluang',
  getParentRoute: () => rootRouteImport,
} as any)
const EksporDokumenRoute = EksporDokumenRouteImport.update({
  id: '/ekspor/dokumen',
  path: '/ekspor/dokumen',
  getParentRoute: () => rootRouteImport,
} as any)
const AnggotaAnggotaIdRoute = AnggotaAnggotaIdRouteImport.update({
  id: '/anggota/$anggotaId',
  path: '/anggota/$anggotaId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inbox': typeof InboxRoute
  '/inventori': typeof InventoriRoute
  '/keuangan': typeof KeuanganRoute
  '/pos': typeof PosRoute
  '/produk-digital': typeof ProdukDigitalRoute
  '/simpan-pinjam': typeof SimpanPinjamRoute
  '/anggota/$anggotaId': typeof AnggotaAnggotaIdRoute
  '/ekspor/dokumen': typeof EksporDokumenRoute
  '/ekspor/peluang': typeof EksporPeluangRoute
  '/anggota/': typeof AnggotaIndexRoute
  '/ekspor/': typeof EksporIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inbox': typeof InboxRoute
  '/inventori': typeof InventoriRoute
  '/keuangan': typeof KeuanganRoute
  '/pos': typeof PosRoute
  '/produk-digital': typeof ProdukDigitalRoute
  '/simpan-pinjam': typeof SimpanPinjamRoute
  '/anggota/$anggotaId': typeof AnggotaAnggotaIdRoute
  '/ekspor/dokumen': typeof EksporDokumenRoute
  '/ekspor/peluang': typeof EksporPeluangRoute
  '/anggota': typeof AnggotaIndexRoute
  '/ekspor': typeof EksporIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inbox': typeof InboxRoute
  '/inventori': typeof InventoriRoute
  '/keuangan': typeof KeuanganRoute
  '/pos': typeof PosRoute
  '/produk-digital': typeof ProdukDigitalRoute
  '/simpan-pinjam': typeof SimpanPinjamRoute
  '/anggota/$anggotaId': typeof AnggotaAnggotaIdRoute
  '/ekspor/dokumen': typeof EksporDokumenRoute
  '/ekspor/peluang': typeof EksporPeluangRoute
  '/anggota/': typeof AnggotaIndexRoute
  '/ekspor/': typeof EksporIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inbox'
    | '/inventori'
    | '/keuangan'
    | '/pos'
    | '/produk-digital'
    | '/simpan-pinjam'
    | '/anggota/$anggotaId'
    | '/ekspor/dokumen'
    | '/ekspor/peluang'
    | '/anggota/'
    | '/ekspor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inbox'
    | '/inventori'
    | '/keuangan'
    | '/pos'
    | '/produk-digital'
    | '/simpan-pinjam'
    | '/anggota/$anggotaId'
    | '/ekspor/dokumen'
    | '/ekspor/peluang'
    | '/anggota'
    | '/ekspor'
  id:
    | '__root__'
    | '/'
    | '/inbox'
    | '/inventori'
    | '/keuangan'
    | '/pos'
    | '/produk-digital'
    | '/simpan-pinjam'
    | '/anggota/$anggotaId'
    | '/ekspor/dokumen'
    | '/ekspor/peluang'
    | '/anggota/'
    | '/ekspor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InboxRoute: typeof InboxRoute
  InventoriRoute: typeof InventoriRoute
  KeuanganRoute: typeof KeuanganRoute
  PosRoute: typeof PosRoute
  ProdukDigitalRoute: typeof ProdukDigitalRoute
  SimpanPinjamRoute: typeof SimpanPinjamRoute
  AnggotaAnggotaIdRoute: typeof AnggotaAnggotaIdRoute
  EksporDokumenRoute: typeof EksporDokumenRoute
  EksporPeluangRoute: typeof EksporPeluangRoute
  AnggotaIndexRoute: typeof AnggotaIndexRoute
  EksporIndexRoute: typeof EksporIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simpan-pinjam': {
      id: '/simpan-pinjam'
      path: '/simpan-pinjam'
      fullPath: '/simpan-pinjam'
      preLoaderRoute: typeof SimpanPinjamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk-digital': {
      id: '/produk-digital'
      path: '/produk-digital'
      fullPath: '/produk-digital'
      preLoaderRoute: typeof ProdukDigitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keuangan': {
      id: '/keuangan'
      path: '/keuangan'
      fullPath: '/keuangan'
      preLoaderRoute: typeof KeuanganRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventori': {
      id: '/inventori'
      path: '/inventori'
      fullPath: '/inventori'
      preLoaderRoute: typeof InventoriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ekspor/': {
      id: '/ekspor/'
      path: '/ekspor'
      fullPath: '/ekspor/'
      preLoaderRoute: typeof EksporIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anggota/': {
      id: '/anggota/'
      path: '/anggota'
      fullPath: '/anggota/'
      preLoaderRoute: typeof AnggotaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ekspor/peluang': {
      id: '/ekspor/peluang'
      path: '/ekspor/peluang'
      fullPath: '/ekspor/peluang'
      preLoaderRoute: typeof EksporPeluangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ekspor/dokumen': {
      id: '/ekspor/dokumen'
      path: '/ekspor/dokumen'
      fullPath: '/ekspor/dokumen'
      preLoaderRoute: typeof EksporDokumenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anggota/$anggotaId': {
      id: '/anggota/$anggotaId'
      path: '/anggota/$anggotaId'
      fullPath: '/anggota/$anggotaId'
      preLoaderRoute: typeof AnggotaAnggotaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InboxRoute: InboxRoute,
  InventoriRoute: InventoriRoute,
  KeuanganRoute: KeuanganRoute,
  PosRoute: PosRoute,
  ProdukDigitalRoute: ProdukDigitalRoute,
  SimpanPinjamRoute: SimpanPinjamRoute,
  AnggotaAnggotaIdRoute: AnggotaAnggotaIdRoute,
  EksporDokumenRoute: EksporDokumenRoute,
  EksporPeluangRoute: EksporPeluangRoute,
  AnggotaIndexRoute: AnggotaIndexRoute,
  EksporIndexRoute: EksporIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
